### ISSUE TITLE
Duplicate dict key warning when run

### ISSUE THREAD

**Issue by Synchro** [shakahl/ansible-percona#1]
I've not mentioned this key at all, this is coming purely from the default role:

`[WARNING]: While constructing a mapping from /usr/local/etc/ansible/roles/shakahl.ansible-percona/defaults/main.yml, line 4, column 1, found a duplicate dict key (mysql_innodb_file_per_table).  Using last defined value only.`

**Comment by DBLaci** [comment]
Thank you! This one is fixed in the master.
